### ISSUE TITLE
How to use OAuth2 with jwt-tokens instead of BasicAuth in fastapi-authz?

### ISSUE THREAD

**Issue by rahulsingh7** [pycasbin/fastapi-authz#14]
Can we use OAuth2 to take a token as input for authentication rather than using BasicAuth with fastapi-authz ?

**Comment by Zxilly** [comment]
Just create a oauth2 backend implement auth interface

**Comment by hsluoyz** [comment]
@Zxilly @Abingcbc can you make a PR to add the JWT support for this repo?

**Comment by hsluoyz** [comment]
@rahulsingh7 can you make a PR?

**Comment by yance-dev** [comment]
@hsluoyz I am very interested in this enhancement，may I craete a PR?

**Comment by Zxilly** [comment]
@yance-dev PR is always welcome~

**Comment by hsluoyz** [comment]
@Nekotoxin

**Comment by Nekotoxin** [comment]
> @Nekotoxin

ok
