### ISSUE TITLE
broken package

### ISSUE THREAD

**Issue by driver2000** [pycasbin/fastapi-authz#8]
Hi all,
I'm trying to install fastapi-authz via pip, but seems there is an error with the dist package : 

```bash
pip install fastapi-authz
Collecting fastapi-authz
  Using cached fastapi-authz-0.0.2.tar.gz (4.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pu2tern5/fastapi-authz_d8d17d7906794d5fa50c26850a619893/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pu2tern5/fastapi-authz_d8d17d7906794d5fa50c26850a619893/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-58f2tko6
         cwd: /tmp/pip-install-pu2tern5/fastapi-authz_d8d17d7906794d5fa50c26850a619893/
    Complete output (159 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pu2tern5/fastapi-authz_d8d17d7906794d5fa50c26850a619893/setup.py", line 16, in <module>
        with open(path.join(here, "requirements.txt"), encoding="utf-8") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-pu2tern5/fastapi-authz_d8d17d7906794d5fa50c26850a619893/requirements.txt'
    # fastapi-authz
    
    fastapi-authz is an authorization middleware for [FastAPI](https://fastapi.tiangolo.com/), it's based
    on [PyCasbin](https://github.com/casbin/pycasbin).
```

**Comment by mdm1983** [comment]
Me too. Same issue with docker

**Comment by hsluoyz** [comment]
@Zxilly plz fix.

**Comment by Zxilly** [comment]
My fault, working on this

**Comment by Zxilly** [comment]
@driver2000 @mdm1983 A package with patch has been pushed to pypi. 
The correspond commit will be later push to Github.
Because I'm working on Continuous Integration, conflicts may be annoyed.

**Comment by driver2000** [comment]
@Zxilly thanks, now it works!

**Comment by Zxilly** [comment]
The issue will close when the fix commit be merged

**Comment by hsluoyz** [comment]
@Zxilly thanks for your work!

We usually do double-release for all Casbin projects that with package manager (like Node.js, Python):

1. GitHub Releases (including git tag)
2. Package manager release (npmjs for Node, pypi for Python)

I saw we already have 5 releases on pypi: https://pypi.org/project/fastapi-authz/#history

![image](https://user-images.githubusercontent.com/3787410/109900895-10661000-7cd3-11eb-8a88-0eb957c515b0.png)

Plz sync them to GitHub Releases ASAP, or there will be many versions or you will forget about which commit a pypi release maps to.

**Comment by Zxilly** [comment]
@hsluoyz have made them
This issue resolved in https://github.com/pycasbin/fastapi-authz/commit/101ae8be8c3fdeafea0490aa0c0430a0ce2e7ab9
